-- 코드를 입력하세요
SELECT FLAVOR 
    FROM (SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER)
    FROM FIRST_HALF A RIGHT OUTER JOIN JULY B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    ORDER BY 2 DESC )
WHERE ROWNUM <= 3

